[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@safe-global/=node_modules/@safe-global/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
